### PR TITLE
Fix compilation issues.

### PR DESCRIPTION
**Pull request by hzeller**
xpost_compat.c: include logging header to access logigng functions used.
xpost_operator.c: include header needed for uintptr_t

### CODE REVIEW

**Comment by hzeller** [comment]
Did you have a chance to look at this ?

**Comment by luser-dr00g** [comment]
Yes, and thank you, and I'm terribly sorry for not responding sooner. The
project is in a bit of a messy state and I have a whole bunch of changes
that haven't propagated to GitHub yet.

One of the many things we've tried to do in the rewriting is to have a
single xpost.h that just includes everything and all internal modules just
include that.

But, until I get all of that pushed, I should probably accept your push.
So, thanks. And thank you also for the reminder. :)

Josh (luser droog)

**Comment by hzeller** [comment]
Yay!

**Comment by luser-dr00g** [comment]
Thanks again. I'm very sorry for the ridiculous delay. Getting back into the project after neglecting it for a while.

**Pull request merged**
